/**
 * Embeds src/brand/questforge-icon.png as a data URI module for the Worker HTML.
 * Source of truth: QuestForge assets/images/icon.png (canonical BrandMark asset).
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

const root = path.resolve(import.meta.dirname, "..");
const pngPath = path.join(root, "src/brand/questforge-icon.png");
const outPath = path.join(root, "src/brand/questforge-icon.ts");

const bytes = readFileSync(pngPath);
if (bytes.length < 32 || bytes[0] !== 0x89 || bytes[1] !== 0x50) {
  throw new Error(`${pngPath} must be a PNG copy of QuestForge assets/images/icon.png`);
}
const dataUri = `data:image/png;base64,${bytes.toString("base64")}`;
const source = `/** Auto-generated by scripts/embed-brand-icon.ts — do not edit by hand. */
export const QUESTFORGE_ICON_DATA_URI = ${JSON.stringify(dataUri)} as const;
`;
writeFileSync(outPath, source);
console.log(`Wrote ${outPath} (${bytes.length} source bytes)`);
